de:
  languageCode: de
  languageName: Deutsch
  contentDir: content/de
  title: Hochzeit
en:
  languageCode: en
  languageName: English
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  contentDir: content/en

